export default {
  gradio: "Gradio",
  inferable: "Inferable",
  milvus: "Milvus",
  ragas: "Ragas",
  openrouter: "OpenRouter",
  firecrawl: "Firecrawl",
  togetherai: "Together.ai",
  xai: "xAI / Grok",
  cohere: "Cohere",
  "fireworks-ai": "Fireworks AI",
  novitaai: "Novita AI",
  cleanlab: "Cleanlab",
  "agno-agents": "Agno Agents",
};
