import type {
  InkeepAIChatSettings,
  InkeepSearchSettings,
  InkeepBaseSettings,
  InkeepModalSettings,
  AIChatDisclaimerSettings,
  InkeepCallbackEvent,
} from "@inkeep/cxkit-react";
import { useTheme } from "next-themes";
import { type PostHog, usePostHog } from "posthog-js/react";

const customAnalyticsCallback = (
  event: InkeepCallbackEvent,
  posthog: PostHog,
): void => {
  const { componentType, conversation } = event.properties;
  const messages = conversation?.messages || [];
  posthog.capture(`inkeep:${event.eventName}`, {
    interactionType: componentType,
    content:
      event.eventName === "user_message_submitted"
        ? messages[messages.length - 1]?.content
        : undefined,
  });
};

type InkeepSharedSettings = {
  baseSettings: InkeepBaseSettings;
  aiChatSettings: InkeepAIChatSettings;
  searchSettings: InkeepSearchSettings;
  modalSettings: InkeepModalSettings;
};

const useInkeepSettings = (): InkeepSharedSettings => {
  const { resolvedTheme } = useTheme();
  const posthog = usePostHog();

  const baseSettings: InkeepBaseSettings = {
    apiKey: process.env.NEXT_PUBLIC_INKEEP_API_KEY! || "",
    primaryBrandColor: "#E11312",
    organizationDisplayName: "Langfuse",
    colorMode: {
      forcedColorMode: resolvedTheme,
    },
    onEvent: (event) => customAnalyticsCallback(event, posthog),
  };

  const modalSettings: InkeepModalSettings = {
    shortcutKey: null,
  };

  const searchSettings: InkeepSearchSettings = {
    placeholder: "Search",
  };

  const disclaimerSettings: AIChatDisclaimerSettings = {
    isEnabled: true,
    label: "AI-generated response",
    tooltip:
      "This response is generated by AI and may contain inaccuracies or errors. Please reach out to support if you need assistance.",
  };

  const aiChatSettings: InkeepAIChatSettings = {
    chatSubjectName: "Langfuse",
    aiAssistantAvatar: "/langfuse-icon.svg",
    introMessage:
      "Hi! I'm Langfuse's AI assistant trained on documentation, help articles, and other content. How can I help you today?",
    isCopyChatButtonVisible: true,
    disclaimerSettings,
    isShareButtonVisible: true,
    shareChatUrlBasePath: "https://langfuse.com/docs/ask-ai",
    getHelpOptions: [
      {
        name: "Contact Support",
        action: {
          type: "open_link",
          url: "/support",
        },
        icon: {
          builtIn: "IoChatbubblesOutline",
        },
      },
    ],
    exampleQuestions: [
      "How can Langfuse help me?",
      "How to use the Python decorator for tracing?",
      "How to set up LLM-as-a-judge evals?",
    ],
  };

  return { baseSettings, aiChatSettings, searchSettings, modalSettings };
};

export default useInkeepSettings;
