import type {
  InkeepAIChatSettings,
  InkeepSearchSettings,
  InkeepBaseSettings,
  InkeepModalSettings,
  AIChatDisclaimerSettings,
  InvokeCallbackAction,
} from "@inkeep/uikit";
import { useTheme } from "nextra-theme-docs";
import { openChat } from "../supportChat";
import { InkeepCallbackEvent } from "@inkeep/uikit";
import { type PostHog, usePostHog } from "posthog-js/react";

const customAnalyticsCallback = (
  event: InkeepCallbackEvent,
  posthog: PostHog
): void => {
  const { interactionType } = event.commonProperties;
  posthog.capture(`inkeep:${event.eventName}`, {
    interactionType,
    content:
      event.eventName === "chat_message_submitted"
        ? event.properties.content
        : undefined,
  });
};

type InkeepSharedSettings = {
  baseSettings: InkeepBaseSettings;
  aiChatSettings: InkeepAIChatSettings;
  searchSettings: InkeepSearchSettings;
  modalSettings: InkeepModalSettings;
};

const useInkeepSettings = (): InkeepSharedSettings => {
  const { resolvedTheme } = useTheme();
  const posthog = usePostHog();

  const baseSettings: InkeepBaseSettings = {
    apiKey: process.env.NEXT_PUBLIC_INKEEP_API_KEY!,
    integrationId: process.env.NEXT_PUBLIC_INKEEP_INTEGRATION_ID!,
    organizationId: process.env.NEXT_PUBLIC_INKEEP_ORGANIZATION_ID!,
    primaryBrandColor: "#E11312", // your brand color, widget color scheme is derived from this
    organizationDisplayName: "Langfuse",
    // ...optional settings
    colorMode: {
      forcedColorMode: resolvedTheme, // to sync dark mode with the widget
    },
    logEventCallback: (event) => customAnalyticsCallback(event, posthog),
    theme: {
      components: {
        SearchBarTrigger: {
          defaultProps: {
            size: "shrink", // 'expand' 'compact' 'shrink' 'medium'
            variant: "subtle", // 'emphasized' 'subtle',
          },
        },
        AIChatPageWrapper: {
          defaultProps: {
            size: "shrink-vertically",
          },
        },
      },
    },
  };

  const modalSettings: InkeepModalSettings = {
    // optional settings

    // deactivate by default, only activated for search bar
    isShortcutKeyEnabled: false,
  };

  const searchSettings: InkeepSearchSettings = {
    placeholder: "Search...",
  };

  const disclaimerSettings: AIChatDisclaimerSettings = {
    isDisclaimerEnabled: true,
    disclaimerLabel: "AI-generated response",
    disclaimerTooltip:
      "This response is generated by AI and may contain inaccuracies or errors. Please reach out to support if you need assistance.",
  };

  const contactSupportCallToAction: InvokeCallbackAction = {
    type: "INVOKE_CALLBACK",
    callback: (args) => {
      if (args.messages.length === 0) {
        openChat();
        return;
      }

      const draftMessage =
        "I tried to get answers via the AI chat but was unable to. My questions were:\n\n" +
        args.messages
          .filter((message) => message.role === "user")
          .map((message) => message.content)
          .join("\n");

      openChat(draftMessage);
    },
    shouldCloseModal: false,
  };

  const aiChatSettings: InkeepAIChatSettings = {
    // optional settings
    chatSubjectName: "Langfuse",
    botAvatarSrcUrl: "/icon256.png", // use your own bot avatar
    introMessage:
      "Hi! I'm Langfuse's AI assistant trained on documentation, help articles, and other content. How can I help you today?",
    shouldShowCopyChatButton: true,
    disclaimerSettings,
    isChatSharingEnabled: true,
    shareChatUrlBasePath: "https://langfuse.com/docs/ask-ai",
    includeAIAnnotations: {
      shouldEscalateToSupport: true,
    },
    aiAnnotationPolicies: {
      shouldEscalateToSupport: [
        {
          threshold: "STANDARD", // "STRICT" or "STANDARD"
          action: {
            type: "SHOW_SUPPORT_BUTTON",
            label: "Contact Support",
            icon: { builtIn: "LuUsers" },
            action: contactSupportCallToAction,
          },
        },
      ],
    },
    getHelpCallToActions: [
      {
        name: "Contact Support",
        ...contactSupportCallToAction,
        icon: {
          builtIn: "IoChatbubblesOutline",
        },
      },
    ],
    quickQuestions: [
      "How can Langfuse help me?",
      "How to use the Python decorator for tracing?",
      "How to set up LLM-as-a-judge evals?",
    ],
  };

  return { baseSettings, aiChatSettings, searchSettings, modalSettings };
};

export default useInkeepSettings;
