const cookbookRoutes = require("./cookbook/_routes.json");

// Generated by scripts/generate-sitemap-excludes.js (runs during prebuild).
// Contains paths with noindex:true or a canonical pointing to a different URL.
let sitemapExcludes = [];
try {
    sitemapExcludes = require("./.sitemap-excludes.json");
} catch {
    // File not yet generated (e.g. first run without prebuild). Silently ignore.
}

/** @type {import('next-sitemap').IConfig} */
module.exports = {
    siteUrl: process.env.CF_PAGES_URL ?? 'https://langfuse.com',
    generateRobotsTxt: true,
    changefreq: 'daily',
    additionalPaths: async (config) => [{
        loc: '/',
        priority: 1,
        changefreq: 'daily',
        lastmod: new Date().toISOString()
    }],
    exclude: [
        // Exclude non-canonical pages from sitemap which are also part of the docs
        ...cookbookRoutes
            .filter(({ docsPath }) => !!docsPath)
            .map(({ notebook }) => `/guides/cookbook/${notebook.replace(".ipynb", "")}`),
        // Exclude _meta files
        '*/_meta',
        '/events/*',
        // Pages with noindex:true or a canonical override (generated by prebuild script)
        ...sitemapExcludes,
        // Exclude API routes for static export
        ...(process.env.STATIC_EXPORT === 'true' ? ['/api/*'] : [])
    ],

}