[project]
name = "langfuse-cookbook"
version = "0.1.0"
description = "Python environment for the Langfuse Cookbook"
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = []

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "uv>=0.7.22",
]
