import { MenuSwitcher } from "@/components/MenuSwitcher";

export default {
  "-- Switcher": {
    type: "separator",
    title: <MenuSwitcher />,
  },
  index: "Overview",
  configuration: "Configuration",
  "license-key": "License Key",
  troubleshooting: "Troubleshooting",
  scaling: "Scaling",
  "-- Deployment": {
    type: "separator",
    title: "Deployment",
  },
  "docker-compose": "Local/VM (Docker Compose)",
  "kubernetes-helm": "Kubernetes (Helm)",
  aws: "AWS (Terraform)",
  azure: "Azure (Terraform)",
  gcp: "GCP (Terraform)",
  railway: "Railway",
  infrastructure: "Infrastructure",
  "-- Security": {
    type: "separator",
    title: "Security",
  },
  "authentication-and-sso": "Authentication and SSO",
  "data-masking": {
    title: "Data Masking ↗ (main docs)",
    href: "/docs/tracing-features/masking",
    newWindow: true,
  },
  encryption: "Encryption",
  "deployment-strategies": "Deployment Strategies",
  rbac: {
    title: "RBAC ↗ (main docs)",
    href: "/docs/rbac",
    newWindow: true,
  },
  "data-retention": {
    title: "Data Retention ↗ (main docs)",
    href: "/docs/data-retention",
    newWindow: true,
  },
  networking: "Networking",
  "-- Features": {
    type: "separator",
    title: "Features",
  },
  "automated-access-provisioning": "Automated Access Provisioning",
  "custom-base-path": "Custom Base Path",
  "headless-initialization": "Headless Initialization",
  "organization-creators": "Organization Creators (EE)",
  "transactional-emails": "Transactional Emails",
  "ui-customization": "UI Customization (EE)",
  "organization-management-api": "Organization Management API (EE)",
  "-- Upgrade": {
    type: "separator",
    title: "Upgrade",
  },
  upgrade: "How to Upgrade",
  versioning: "Versioning",
  "background-migrations": "Background Migrations",
  "upgrade-guides": "Upgrade Guides",
  "release-notes": "Release Notes",
  "-- Former Versions": {
    type: "separator",
    title: "Former Versions",
  },
  v2: "v2",
};
