import json
import shutil
import os
import re

# Warning prepended to every generated markdown frontmatter so the .md/.mdx files
# clearly indicate they are auto-generated from the .ipynb sources in cookbook/.
def _generated_source_note(notebook_path: str) -> str:
    """Build the per-file source warning including the upstream notebook path."""
    return (
        f"⚠️ This file is auto-generated from {notebook_path}. "
        f"Do not edit this file directly — update the .ipynb file and "
        f"regenerate with `bash scripts/update_cookbook_docs.sh`."
    )


def _yaml_quote(value: str) -> str:
    """Render a YAML scalar that's always safe to parse (double-quoted).

    Quoting every value avoids breakage on titles that contain `:` (e.g.
    "Example: Monitoring LLM Security"), leading `#`, `[`/`{`, etc.
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _strip_pandas_html_outputs(markdown: str) -> str:
    """Remove raw pandas DataFrame `_repr_html_` output blocks.

    Jupyter cells that return a DataFrame render as a `<div>` containing a
    `<style scoped>` with CSS followed by a `<table>`. The embedded CSS uses
    `{ ... }` which MDX tries to parse as JSX expressions and fails on. These
    blocks carry little value in the docs, so the simplest robust fix is to
    drop them entirely.
    """
    # Match a top-level <div> ... </div> block that contains a <style scoped>
    # (the telltale sign of pandas HTML output). Non-greedy match on outer
    # <div>...</div>, anchored to the start of a line.
    pattern = re.compile(
        r"(?ms)^<div>\s*\n(?:.*?\n)*?</div>\s*$"
    )

    def replace(match):
        block = match.group(0)
        if "<style scoped>" not in block:
            return block
        return ""

    return pattern.sub(replace, markdown)


def _wrap_indented_outputs_in_fences(markdown: str) -> str:
    """Wrap nbconvert-style indented cell outputs in ```text fences.

    nbconvert renders the stdout/repr output of notebook cells as a block of
    lines prefixed with 4 spaces, surrounded by blank lines. CommonMark treats
    that as an indented code block, but MDX still parses any `{...}` or
    `<Tag>` inside it as JSX — which blows up on Python dict reprs and JSON
    responses. Converting these blocks to explicit fenced code blocks makes
    MDX leave them alone entirely.

    Only runs outside of fenced code blocks (``` or ~~~), so Python source
    blocks are untouched.
    """
    lines = markdown.split("\n")
    out: list[str] = []
    i = 0
    fence_open: str | None = None  # None, "```", or "~~~" (tracks open fence marker)
    fence_re = re.compile(r"^( {0,3})(`{3,}|~{3,})")

    def is_indented_output(line: str) -> bool:
        # 4+ leading spaces and non-empty remainder
        return line.startswith("    ") and line.strip() != ""

    while i < len(lines):
        line = lines[i]

        # Track fenced code block state first
        m = fence_re.match(line)
        if m:
            marker = m.group(2)[0] * 3
            if fence_open is None:
                fence_open = marker
            elif marker == fence_open:
                fence_open = None
            out.append(line)
            i += 1
            continue

        # Only rewrite when we're outside any fenced code block and the
        # previous emitted line is blank (or we're at the very start of
        # content). That is the CommonMark condition for an indented code
        # block, which is exactly what nbconvert produces for cell outputs.
        prev_blank = (not out) or (out[-1].strip() == "")
        if fence_open is None and prev_blank and is_indented_output(line):
            block: list[str] = []
            while i < len(lines):
                cur = lines[i]
                if is_indented_output(cur):
                    block.append(cur[4:])
                    i += 1
                    continue
                # Allow blank lines inside the block only if an indented
                # line follows; otherwise the block ends here.
                if cur.strip() == "":
                    j = i + 1
                    while j < len(lines) and lines[j].strip() == "":
                        j += 1
                    if j < len(lines) and is_indented_output(lines[j]):
                        # Preserve interior blank lines.
                        block.extend([""] * (j - i))
                        i = j
                        continue
                break
            out.append("```")
            out.extend(block)
            out.append("```")
            continue

        out.append(line)
        i += 1

    return "\n".join(out)


def _wrap_balanced_braces(text: str) -> str:
    """In a single segment of text (already known to be outside code spans),
    wrap every top-level balanced `{...}` region with backticks so that MDX
    treats it as inline code instead of a JSX expression. Handles nested
    braces correctly.
    """
    out: list[str] = []
    i = 0
    n = len(text)
    while i < n:
        ch = text[i]
        if ch == "{":
            depth = 1
            j = i + 1
            while j < n and depth > 0:
                if text[j] == "{":
                    depth += 1
                elif text[j] == "}":
                    depth -= 1
                j += 1
            if depth == 0:
                out.append("`")
                out.append(text[i:j])
                out.append("`")
                i = j
                continue
        out.append(ch)
        i += 1
    return "".join(out)


def _escape_curly_in_blockquotes(markdown: str) -> str:
    """Wrap `{...}` runs inside blockquote lines with backticks.

    Blockquotes in notebook markdown often contain pasted tool output such as
    `Topics detected scores={'violence': 0.9}` or multi-line Python dicts
    (including nested ones), which MDX tries (and fails) to parse as JSX
    expressions. Wrapping the offending `{...}` in backticks makes MDX treat
    them as inline code. Only operates outside fenced code blocks.
    """
    lines = markdown.split("\n")
    fence_re = re.compile(r"^( {0,3})(`{3,}|~{3,})")
    fence_open: str | None = None
    out: list[str] = []
    for line in lines:
        m = fence_re.match(line)
        if m:
            marker = m.group(2)[0] * 3
            if fence_open is None:
                fence_open = marker
            elif marker == fence_open:
                fence_open = None
            out.append(line)
            continue
        if fence_open is None and re.match(r"^\s{0,3}>", line):
            # Split by existing inline code spans (backticks); only rewrite
            # segments that are not already inside backticks.
            parts = line.split("`")
            for idx in range(0, len(parts), 2):
                parts[idx] = _wrap_balanced_braces(parts[idx])
            line = "`".join(parts)
        out.append(line)
    return "\n".join(out)


_STYLE_ATTR_RE = re.compile(r'style="([^"]*)"')


def _css_to_jsx_style(css: str) -> str:
    """Convert a CSS declaration string into a JSX style object literal."""
    entries = []
    for decl in css.split(";"):
        decl = decl.strip()
        if not decl or ":" not in decl:
            continue
        key, _, value = decl.partition(":")
        key = key.strip()
        value = value.strip()
        if not key or not value:
            continue
        # Convert CSS kebab-case or vendor prefix to camelCase.
        parts = key.split("-")
        if parts[0] == "":
            # Vendor prefix e.g. -webkit-transform -> WebkitTransform
            parts = [p.capitalize() for p in parts[1:]]
        else:
            parts = [parts[0]] + [p.capitalize() for p in parts[1:]]
        js_key = "".join(parts)
        escaped = value.replace("\\", "\\\\").replace("'", "\\'")
        entries.append(f"'{js_key}': '{escaped}'")
    return "{{" + ", ".join(entries) + "}}"


def _convert_html_style_attrs(markdown: str) -> str:
    """Rewrite `style="..."` (CSS string) to JSX `style={{...}}` object form.

    Notebooks occasionally include raw HTML with a CSS string style attribute
    (e.g. `<div style="position: relative;">`). React/JSX only accepts an
    object literal, so without this conversion the page throws at render time.
    Only operates outside fenced code blocks.
    """
    lines = markdown.split("\n")
    fence_re = re.compile(r"^( {0,3})(`{3,}|~{3,})")
    fence_open: str | None = None
    out: list[str] = []
    for line in lines:
        m = fence_re.match(line)
        if m:
            marker = m.group(2)[0] * 3
            if fence_open is None:
                fence_open = marker
            elif marker == fence_open:
                fence_open = None
            out.append(line)
            continue
        if fence_open is None:
            line = _STYLE_ATTR_RE.sub(
                lambda mo: f"style={_css_to_jsx_style(mo.group(1))}", line
            )
        out.append(line)
    return "\n".join(out)


def _self_close_void_tags(markdown: str) -> str:
    """Rewrite bare `<br>` / `<hr>` tags as self-closing (`<br />`).

    MDX requires all HTML tags to either have a matching close tag or be
    self-closing; Jupyter-generated content often contains bare `<br>`.
    Only operates outside fenced code blocks.
    """
    lines = markdown.split("\n")
    fence_re = re.compile(r"^( {0,3})(`{3,}|~{3,})")
    fence_open: str | None = None
    tag_re = re.compile(r"<(br|hr)(\s[^>]*)?>(?!\s*</\1>)", re.IGNORECASE)
    out: list[str] = []
    for line in lines:
        m = fence_re.match(line)
        if m:
            marker = m.group(2)[0] * 3
            if fence_open is None:
                fence_open = marker
            elif marker == fence_open:
                fence_open = None
            out.append(line)
            continue
        if fence_open is None:
            line = tag_re.sub(lambda mo: f"<{mo.group(1)}{mo.group(2) or ''} />", line)
        out.append(line)
    return "\n".join(out)


# Function to transform custom metadata, tabs, callouts, steps, and components
def transform_content_to_mdx(markdown_content, notebook_path: str = ""):
    was_transformed_overall = False
    metadata_was_processed = False 
    content_for_processing = markdown_content 
    generated_yaml_frontmatter = "" 

    attribute_parser_regex = re.compile(r'(\w+):\s*"([^"]*)"')

    # --- Stage 1: Custom Notebook Metadata Comment to YAML Frontmatter ---
    metadata_at_start_pattern = re.compile(
        r"^\s*(<!--\s*NOTEBOOK_METADATA\s*(.*?)\s*-->)\s*\n?(.*)",
        re.DOTALL
    )
    match_at_start = metadata_at_start_pattern.match(content_for_processing)
    if match_at_start:
        metadata_was_processed = True 
        was_transformed_overall = True 
        attributes_string = match_at_start.group(2).strip()
        content_after_comment = match_at_start.group(3)
        yaml_lines = []
        for attr_match in attribute_parser_regex.finditer(attributes_string):
            key = attr_match.group(1)
            value = attr_match.group(2)
            # Drop any `source` key from the .ipynb metadata — the source warning
            # is injected below so the .ipynb itself no longer needs to carry it.
            if key == "source":
                continue
            # Always double-quote values so titles/descriptions that contain
            # `:`, `#`, brackets, etc. don't break the YAML parser.
            yaml_lines.append(f"{key}: {_yaml_quote(value)}")
        # Always prepend the source warning so every generated markdown file
        # indicates it is auto-generated and should not be edited directly,
        # naming the upstream notebook so readers know where to edit instead.
        source_line = f"source: {_yaml_quote(_generated_source_note(notebook_path))}"
        generated_yaml_frontmatter = (
            "---\n" + source_line + "\n" + "\n".join(yaml_lines) + "\n---\n\n"
        )
        content_for_processing = content_after_comment
    
    # --- Stage 2: Tab Transformation --- 
    master_tabs_pattern = re.compile(
        r"<!--\s*TABS_START\s*items:\s*(\[.*?\])\s*-->(.*?)<!--\s*TABS_END\s*-->",
        re.DOTALL | re.MULTILINE
    )
    def replace_tabs_block_match(match_obj):
        nonlocal was_transformed_overall 
        was_transformed_overall = True 
        items_list_str_from_comment = match_obj.group(1)
        inner_content_of_tabs_block = match_obj.group(2)
        parsed_items_for_tabs_prop = []
        try:
            json_compatible_items_str = items_list_str_from_comment.replace("'", '"')
            parsed_items_for_tabs_prop = json.loads(json_compatible_items_str)
        except json.JSONDecodeError:
            print(f"Warning: Could not parse 'items' attribute from TABS_START comment: {items_list_str_from_comment}")
            return match_obj.group(0) 
        mdx_individual_tab_components = []
        tab_item_pattern = re.compile(
            r"<!--\s*TAB_ITEM_START\s+title:\s*\"(.*?)\"\s*-->(.*?)<!--\s*TAB_ITEM_END\s*-->",
            re.DOTALL | re.MULTILINE
        )
        found_tab_items = False
        for item_match in tab_item_pattern.finditer(inner_content_of_tabs_block):
            found_tab_items = True
            content_of_tab_item = item_match.group(2).strip()
            mdx_individual_tab_components.append(f"<Tab>\n{content_of_tab_item}\n</Tab>")
        if not found_tab_items:
            print(f"Warning: TABS_START/TABS_END block found but no TAB_ITEM_START/END children. Original content kept.")
            return match_obj.group(0)
        items_prop_for_mdx = json.dumps(parsed_items_for_tabs_prop)
        return f"<Tabs items={{{items_prop_for_mdx}}}>\n" + "\n".join(mdx_individual_tab_components) + "\n</Tabs>"
    content_for_processing = master_tabs_pattern.sub(replace_tabs_block_match, content_for_processing)

    # --- Stage 3: Callout Transformation --- 
    callout_block_pattern = re.compile(
        r"<!--\s*CALLOUT_START\s*(.*?)\s*-->(.*?)<!--\s*CALLOUT_END\s*-->",
        re.DOTALL | re.MULTILINE
    )
    def replace_callout_block_match(match_obj):
        nonlocal was_transformed_overall
        was_transformed_overall = True
        attributes_string_from_comment = match_obj.group(1)
        content_of_callout = match_obj.group(2).strip()
        props_for_mdx_component = []
        for attr_match in attribute_parser_regex.finditer(attributes_string_from_comment):
            key = attr_match.group(1)
            value = attr_match.group(2)
            props_for_mdx_component.append(f'{key}="{value}"')
        props_string = " ".join(props_for_mdx_component)
        if props_string: props_string = " " + props_string
        return f"<Callout{props_string}>\n{content_of_callout}\n</Callout>"
    content_for_processing = callout_block_pattern.sub(replace_callout_block_match, content_for_processing)

    # --- Stage 4: Steps Transformation (Simplified) ---
    # This pattern will find blocks starting with <!-- STEPS_START -->
    # and ending with <!-- STEPS_END -->, capturing the content in between.
    steps_simplified_pattern = re.compile(
        r"<!--\s*STEPS_START\s*-->(.*?)<!--\s*STEPS_END\s*-->",
        re.DOTALL | re.MULTILINE
    )
    def replace_steps_simplified_match(match_obj):
        nonlocal was_transformed_overall
        was_transformed_overall = True 
        # Group 1 is the content between STEPS_START and STEPS_END
        inner_content = match_obj.group(1).strip() 
        # The inner_content is directly placed inside <Steps>
        # If your <Steps> component in MDX expects child <Step> components,
        # you would need to ensure the Markdown content *within* the STEPS_START/END
        # is structured in a way that MDX can interpret as individual steps,
        # or that the <Steps> component itself handles raw Markdown children appropriately.
        # For this transformation, we are just wrapping the block.
        return f"<Steps>\n{inner_content}\n</Steps>"
        
    content_for_processing = steps_simplified_pattern.sub(replace_steps_simplified_match, content_for_processing)
    
    # --- Stage 5: Component Transformation ---
    component_comment_pattern = re.compile(
        r'<!--\s*(?:COMPONENT|MARKDOWN_COMPONENT)\s*(.*?)\s*-->',
        re.DOTALL | re.MULTILINE
    )
    imports_seen: set[str] = set()

    def replace_component_comment(match_obj):
        nonlocal was_transformed_overall, imports_seen
        was_transformed_overall = True
        attr_string = match_obj.group(1)
        attrs = {k: v for k, v in attribute_parser_regex.findall(attr_string)}
        title = attrs.pop("title", "").strip() or attrs.pop("name", "").strip()
        path  = attrs.pop("path", "").strip()
        other_props = " ".join(f'{k}="{v}"' for k, v in attrs.items())
        import_stmt = ""
        if title and path and title not in imports_seen:
            imports_seen.add(title)
            import_stmt = f'import {title} from "{path}";\n\n'
        props_str = f" {other_props}" if other_props else ""
        component_usage = f"<{title}{props_str} />" 
        if import_stmt:
            return f'{import_stmt}{component_usage}'
        else:
            return component_usage
    content_for_processing = component_comment_pattern.sub(replace_component_comment, content_for_processing)

    # --- Stage 6: Normalize nbconvert output so MDX can parse it ---
    # Strip pandas DataFrame `_repr_html_` blocks first — these contain CSS
    # with `{ ... }` inside a `<style>` tag that MDX can't parse and would
    # otherwise confuse the indented-output detector below.
    # Then wrap 4-space-indented notebook cell outputs (which may contain
    # `{...}` or `<...>`) in explicit code fences, and self-close any bare
    # void HTML tags like `<br>` so acorn doesn't choke on them.
    content_for_processing = _strip_pandas_html_outputs(content_for_processing)
    content_for_processing = _wrap_indented_outputs_in_fences(content_for_processing)
    content_for_processing = _escape_curly_in_blockquotes(content_for_processing)
    content_for_processing = _convert_html_style_attrs(content_for_processing)
    content_for_processing = _self_close_void_tags(content_for_processing)

    final_assembled_content = generated_yaml_frontmatter + content_for_processing
    
    return final_assembled_content, was_transformed_overall, metadata_was_processed

# --- Main script execution logic (remains the same) ---
try:
    with open('./cookbook/_routes.json', 'r', encoding='utf-8') as file:
        mappings = json.load(file)
except FileNotFoundError:
    print("Error: './cookbook/_routes.json' not found. Exiting.")
    exit(1)
except json.JSONDecodeError:
    print("Error: Could not decode JSON from './cookbook/_routes.json'. Exiting.")
    exit(1)

for mapping in mappings:
    notebook_filename = mapping.get('notebook')
    if not notebook_filename:
        print(f"Warning: Skipping mapping due to missing 'notebook' field: {mapping}")
        continue

    md_source_filename = notebook_filename.replace('.ipynb', '.md')
    source_path = os.path.join('cookbook', md_source_filename)

    if not os.path.exists(source_path):
        print(f"Warning: Source file {source_path} not found. Skipping.")
        continue

    try:
        with open(source_path, 'r', encoding='utf-8') as f:
            original_md_content = f.read()
    except Exception as e:
        print(f"Error reading source file {source_path}: {e}. Skipping.")
        continue
    
    notebook_repo_path = f"cookbook/{notebook_filename}"
    processed_content_final, was_transformed_final, metadata_found = transform_content_to_mdx(
        original_md_content, notebook_path=notebook_repo_path
    )
    
    output_extension = ".mdx" if metadata_found else ".md"
    
    filename_base_no_ext = notebook_filename.replace('.ipynb', '')

    destination_paths_to_write = []
    docs_path_value = mapping.get('docsPath')
    if docs_path_value is not None:
        path_parts = docs_path_value.split('/')
        base_filename_from_docs_path = path_parts[-1]
        if '.' in base_filename_from_docs_path:
            name_without_ext = base_filename_from_docs_path.rsplit('.', 1)[0]
        else:
            name_without_ext = base_filename_from_docs_path
        if len(path_parts) > 1:
            dir_path_from_docs_path = os.path.join(*path_parts[:-1])
            final_docs_path_filename_part = name_without_ext + output_extension
            dest_path_str = os.path.join("content", dir_path_from_docs_path, final_docs_path_filename_part)
        else:
             dest_path_str = os.path.join("content", name_without_ext + output_extension)
        destination_paths_to_write.append(dest_path_str)

    # Only add to guides/cookbook if the mapping is marked as a guide (default True)
    if mapping.get('isGuide', True):
        guide_dest_filename = filename_base_no_ext + output_extension
        guide_dest_path_str = os.path.join("content", "guides", "cookbook", guide_dest_filename)
        destination_paths_to_write.append(guide_dest_path_str)

    for full_destination_path in destination_paths_to_write:
        os.makedirs(os.path.dirname(full_destination_path), exist_ok=True)
        
        print(f"Processing: {notebook_filename} -> {full_destination_path} (Overall Transformed: {was_transformed_final}, Metadata Found: {metadata_found})")
        try:
            with open(full_destination_path, 'w', encoding='utf-8') as f_out:
                f_out.write(processed_content_final)
        except Exception as e:
            print(f"Error writing to destination file {full_destination_path}: {e}")

    try:
        os.remove(source_path)
    except Exception as e:
        print(f"Error removing source file {source_path}: {e}")

print("\nDone processing cookbook files!")