export default {
  overview: "Overview",
  openai: "OpenAI SDK",
  openaiagentssdk: "OpenAI Agents SDK",
  langchain: "Langchain",
  "llama-index": "LlamaIndex",
  haystack: "Haystack",
  litellm: "LiteLLM",
  "vercel-ai-sdk": "Vercel AI SDK",
  "strands-agents": "AWS Strands Agents",
  autogen: "AutoGen",
  "semantic-kernel": "Semantic Kernel",
  "pydantic-ai": "Pydantic AI",
  dify: "Dify.AI",
  databricks: "Databricks",
  instructor: "Instructor",
  dspy: "DSPy",
  ollama: "Ollama",
  mirascope: "Mirascope",
  flowise: "Flowise",
  langflow: "Langflow",
  bedrock: "Amazon Bedrock",
  "google-vertex-ai": "Google Vertex AI",
  "google-adk": "Google ADK",
  "mistral-sdk": "Mistral SDK",
  promptfoo: "Promptfoo",
  openwebui: "OpenWebUI",
  lobechat: "LobeChat",
  huggingface: "Huggingface",
  deepseek: "DeepSeek",
  "groq-sdk": "Groq",
  vapi: "Vapi",
  goose: "Goose",
  smolagents: "Smolagents",
  crewai: "CrewAI",
  "spring-ai": "Spring AI",
  "quarkus-langchain4j": "Quarkus LangChain4j",
  mastra: "Mastra",
  voltagent: "VoltAgent",
  ragflow: "Ragflow",
  other: "More Ways to Integrate",
};
