export default {
  overview: "Overview",
  openai: "OpenAI SDK",
  langchain: "Langchain",
  "llama-index": "LlamaIndex",
  haystack: "Haystack",
  litellm: "LiteLLM",
  "vercel-ai-sdk": "Vercel AI SDK",
  autogen: "AutoGen",
  dify: "Dify.AI",
  instructor: "Instructor",
  dspy: "DSPy",
  ollama: "Ollama",
  mirascope: "Mirascope",
  flowise: "Flowise",
  langflow: "Langflow",
  "amazon-bedrock": "Amazon Bedrock",
  "google-vertex-ai": "Google Vertex AI",
  "mistral-sdk": "Mistral SDK",
  promptfoo: "Promptfoo",
  openwebui: "OpenWebUI",
  lobechat: "LobeChat",
  huggingface: "Huggingface",
  deepseek: "DeepSeek",
  "groq-sdk": "Groq",
  vapi: "Vapi",
  goose: "Goose",
  other: "More Ways to Integrate",
};
