export default {
  overview: "Overview",
  openai: "OpenAI SDK",
  langchain: "Langchain",
  "llama-index": "LlamaIndex",
  haystack: "Haystack",
  litellm: "LiteLLM",
  "vercel-ai-sdk": "Vercel AI SDK",
  dify: "Dify.AI",
  instructor: "Instructor",
  dspy: "DSPy",
  ollama: "Ollama",
  mirascope: "Mirascope",
  flowise: "Flowise",
  langflow: "Langflow",
  "amazon-bedrock": "Amazon Bedrock",
  "mistral-sdk": "Mistral SDK",
  "lamatic": "Lamatic",
  "promptfoo": "Promptfoo",
  "openwebui": "OpenWebUI",
  other: "More Ways to Integrate",
};
