export default {
  sessions: "Sessions",
  users: "Users", 
  environments: "Environments",
  tags: "Tags", 
  metadata: "Metadata",
  "trace-ids": "Trace IDs & Distributed Tracing",
  "releases-and-versioning": "Releases & Versioning",
  "multi-modality": "Multi-Modality & Attachments",
  comments: "Comments",
  "agent-graphs": "Agent Graphs",
  url: "Trace URLs",
  "log-levels": "Log Levels",
  masking: "Masking",  
  sampling: "Sampling",
}; 