export default {
  index: "Overview",
  "-- Security": {
    type: "separator",
    title: "Security",
  },
  auth: "Authentication & Authorization",
  encryption: "Encryption",
  "data-regions": "Data Regions & Availability",
  dependencies: "Software Dependencies",
  "incident-and-breach": "Incident & Breach",
  "responsible-disclosure": "Responsible Disclosure",
  whistleblowing: "Whistleblowing",
  "penetration-testing": "Penetration Testing",
  subprocessors: "Subprocessors",
  "vulnerability-management": "Vulnerability Management",
  "-- Compliance": {
    type: "separator",
    title: "Compliance",
  },
  policies: "Policies",
  soc2: "SOC 2 Type II",
  iso27001: "ISO 27001",
  hipaa: "HIPAA",
  "-- Privacy": {
    type: "separator",
    title: "Privacy",
  },
  dpa: "DPA",
  gdpr: "GDPR",
  "manage-personal-data": "Managing Personal Data",
  "privacy-faq": "Privacy FAQ",
};
