export default {
  index: "Overview",
  "-- Security": {
    type: "separator",
    title: "Security",
  },
  auth: "Authentication & Authorization",
  "audit-logs": {
    title: "Audit Logs ↗",
    href: "/docs/audit-logs",
    newWindow: true,
  },
  encryption: "Encryption",
  "data-regions": "Data Regions & Availability",
  networking: "Networking & IP Ranges",
  dependencies: "Software Dependencies",
  "incident-and-breach": "Incident & Breach",
  "responsible-disclosure": "Responsible Disclosure",
  whistleblowing: "Whistleblowing",
  "penetration-testing": "Penetration Testing",
  "vulnerability-management": "Vulnerability Management",
  "-- Compliance": {
    type: "separator",
    title: "Compliance",
  },
  policies: "Policies",
  soc2: "SOC 2 Type II",
  iso27001: "ISO 27001",
  hipaa: "HIPAA",
  "-- Privacy": {
    type: "separator",
    title: "Privacy",
  },
  dpa: "DPA",
  subprocessors: "Subprocessors",
  gdpr: "GDPR",
  "manage-personal-data": "Managing Personal Data",
  "privacy-faq": "Privacy FAQ",
  "-- Legal": {
    type: "separator",
    title: "Legal",
  },
  terms: {
    title: "Terms of Service ↗",
    href: "/terms",
    newWindow: true,
  },
  privacy: {
    title: "Privacy Policy ↗",
    href: "/privacy",
    newWindow: true,
  },
};
