name: Index Plain Knowledge Docs

on:
  schedule:
    - cron: "0 3 * * *" # 3am every day
  workflow_dispatch:

permissions: {}

jobs:
  index-plain-knowledge-docs:
    name: Index Plain Knowledge Docs
    environment: "main"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22

      - name: Index Langfuse.com
        run: npx --yes @team-plain/cli@0.4.0 index-sitemap https://langfuse.com/sitemap-0.xml
        env:
          PLAIN_API_KEY: ${{ secrets.PLAIN_API_KEY_WRITE_INDEXED_DOCUMENTS }}

      - name: Index GH Discussions
        run: npx --yes @team-plain/cli@0.4.0 index-sitemap https://langfuse.com/github-discussions-sitemap.xml
        env:
          PLAIN_API_KEY: ${{ secrets.PLAIN_API_KEY_WRITE_INDEXED_DOCUMENTS }}
