---
name: Check GitHub Actions

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  merge_group:
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  zizmor:
    name: Check GitHub Actions security
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
        with:
          advanced-security: true
